### ISSUE TITLE
temporary playbook not exist

### ISSUE THREAD

**Issue by mmiladi** [usegalaxy-eu/operations#1]
At https://github.com/usegalaxy-eu/operations/edit/master/README.md line 16, the referred file https://github.com/usegalaxy-eu/galaxy-playbook-temporary/blob/master/roles/galaxy_config/vars/subsites.yml does not exist.

**Comment by bgruening** [comment]
Its here: https://github.com/usegalaxy-eu/galaxy-playbook-temporary/blob/master/roles/galaxy_config/vars/subsites.yml

But I guess you can not access it?

**Comment by mmiladi** [comment]
True, not accessible

**Comment by mmiladi** [comment]
Also this one have no access, we can put all tools from docker-galaxy-graphclust + probably docker-galaxy-rna-workbench within
https://github.com/usegalaxy-eu/galaxy-playbook-temporary/blob/master/roles/galaxy_config/templates/global_host_filters.py.j2

**Comment by mmiladi** [comment]
Certainly! Enjoy ur vac!

**Comment by erasche** [comment]
Solved now :)
